-- ==========================================================
-- Saraswati Motors - True Value Database Setup Script
-- ==========================================================
-- INSTRUCTIONS:
-- 1. Go to your Supabase Dashboard (https://supabase.com)
-- 2. Open your Project and go to the "SQL Editor" tab on the left sidebar
-- 3. Click "New Query", paste this entire script, and click "Run"
-- ==========================================================

-- 1. Drop existing tables if they exist to avoid schema conflicts
DROP TABLE IF EXISTS public.vehicles CASCADE;
DROP TABLE IF EXISTS public.inquiries CASCADE;

-- 2. Create the central vehicles inventory table matching frontend columns
CREATE TABLE public.vehicles (
    id TEXT PRIMARY KEY,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    variant TEXT,
    year INTEGER NOT NULL,
    mileage_km INTEGER NOT NULL,
    fuel_type TEXT NOT NULL,
    transmission TEXT NOT NULL,
    price_lakh NUMERIC NOT NULL,
    location TEXT NOT NULL,
    is_certified BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    badge TEXT,
    engine TEXT,
    max_power TEXT,
    seating_capacity TEXT,
    ownership TEXT,
    insurance TEXT,
    description TEXT,
    image_url TEXT NOT NULL,
    gallery TEXT[],
    details JSONB
);

-- 3. Create the inquiries/leads table matching enquire forms
CREATE TABLE public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    vehicle_id TEXT,
    vehicle_name TEXT,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email_address TEXT
);

-- 4. Grant table privileges to the anonymous and authenticated API roles
GRANT SELECT ON public.vehicles TO anon;
GRANT SELECT ON public.vehicles TO authenticated;
GRANT INSERT ON public.inquiries TO anon;
GRANT INSERT ON public.inquiries TO authenticated;

-- 5. Enable Row-Level Security (RLS) on both tables
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS policies to allow public read on vehicles and public insert on inquiries
CREATE POLICY "Allow public read access to vehicles" 
ON public.vehicles FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public insert access to inquiries" 
ON public.inquiries FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 7. Seed the database with the pre-owned certified vehicles
INSERT INTO public.vehicles (
    id, make, model, variant, year, mileage_km, fuel_type, transmission, 
    price_lakh, location, is_certified, is_featured, badge, engine, 
    max_power, seating_capacity, ownership, insurance, description, 
    image_url, gallery, details
) VALUES 
(
    'xl6-2021', 'Maruti Suzuki', 'XL6', 'Alpha MT', 2021, 24500, 'Petrol', 'Manual', 
    9.85, 'Jhunsi, Prayagraj', true, true, 'Featured', '1462 cc, K15B', 
    '103 bhp @ 6000 rpm', '6 Seater (Captain Seats)', 'First Owner', 'Comprehensive (Valid Oct 2025)', 
    'This pristine 2021 Maruti Suzuki XL6 Alpha is a top-of-the-line variant, certified by Maruti Suzuki True Value. Features captain seats in the second row, leather interiors, and Smart Hybrid Petrol efficiency.', 
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDITYFHj1B-X4XYY9Jplq9tZDx2L8kvaMDXKzb6zmL_RBDt2yNdLi6AKeDg7rnBaSzD-FmHFWTLxDWFwcnlCmCtHCEFcTxnL6fcvVzD6jh_RlSknq_WNSSjrR6bTi1m0uiPR0OwJFQl6LQv3jbdxXAFNib7Svtfmbt7lLXB8zX7YwljYfAwybjnYo7shgy17fpo5MNx0DlFXE8os5fhldeWNxhKpaFBzFIJ3qL45LxsF8IHp7j84VOJIPWmiNPcX9NI5OpUp4IbVzWd', 
    ARRAY[
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDcfNw_A7LwuCppVupA_uBZoiyCc5arGWGpj-dMNGQeo3HlfV90V7cX9Nwa3clLCYghnDKXtiLIkew9NCdML8r4AYEOw5bLy0IIox1ijJpe1QPoKMf0GiISKWC77PMC1meXYcEo9sbZbv7gEQ7ipjdtn-u_O98UgT63479uNWl_tdJiEFlzJMHp0FtBQbhfpKaqc-m5C9IYTIyU-VT6JgNzMlOpqkkNiTS-u8VoUxjcq9VjPrGpsED55MslaMMJ1W0yUGDZbjM9SFe-',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDoLiI_IFt3LP6q_N9HfSI2UIkoQOfuAwL0WlQFiu4CcJzgMdQIzuoNZqsrDfY7bpQSoOuw14Czcp-XWlLbOTXGSgo6uh69q4klY5MyO2GabqtKyTpuu2r3nchmla7iTXt8YuEuMU4fA9bJnCrpoa2nqzzITg5pp9cYjCXEkGtGRzoarFzaYUAkdVOVEE3B2OwnpvmT3A5-8fspy3I09cMV__fgH79Zybi8mXD1q1aV-QcZw1EMRC3JJExx5ynqzynj6Oq1RGBYF-o9',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAR_O0OZRsfc5ip8BupgFkbBnw385UDprRZqvJweHYYwLnqfMjRdxWLxO6sHegmnW-1EoeupQSCn24AjFO1zT7htlOgA-1UxdCEm-imWpEGcA50ChmEQXDVFEIL-ZNp6nsNi8UjHOhDINy-s5aJe74pryqDc63Coj4IzzOBvJ-OixXSVRSfG8RasFPaDOqJR5eDYTUVQAPAoBbO5nubxU9Rfj2lpULcq9Dy6BPqyHOrUVKcap7m6T0RBewy6O',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBOKHW627YRZ2z_sSm3nCy84YI8UHOJY08SG1eLBcez2f8OemKIDp6uG_-L6R8I5qvjPABu_gdTHP2AsShOxu8f_Odnww_VtScK1MMzhfzaFlw8eNfqZmYdVCSs89oUuHzekqPwmuf6N6JaEnKuICKfPvtoi7afckH3HbXrlctLAjsqkB-oMRN2tvg_nGtWlkpxk7gudgwgMRRiX6BAyLSUOFXJVh5eUrMoGWMkn4xvTk5AxV8-c34prGt9Nc6E-58KMxPZqX-m2FhS'
    ], 
    '{"mileage": "19.01 kmpl", "engine_capacity": "1462 cc", "max_power": "103 bhp @ 6000 rpm"}'::jsonb
),
(
    'baleno-2022', 'Maruti Suzuki', 'Baleno', 'Alpha 1.2L DualJet', 2022, 14200, 'Petrol', 'Manual', 
    8.45, 'Jhunsi, Prayagraj', true, true, 'Featured', '1197 cc, DualJet', 
    '89 bhp @ 6000 rpm', '5 Seater', 'First Owner', 'Comprehensive (Valid Oct 2025)', 
    'This pristine 2022 Maruti Suzuki Baleno Alpha is a top-of-the-line variant, meticulously maintained and certified by Maruti Suzuki True Value. It features the powerful yet efficient 1.2L DualJet engine. The vehicle has been through a 376-point quality check, ensuring a reliable and premium ownership experience.', 
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA7vznq29wfSYWA-3E7DCGn460U9S_K-ZnCCU_1Q9_IlgUuhSFZaIft8rkIxLGcP4nVMomqC--MG4TQfmgQiu3Xlp-e9rE_j8p22tpKtj7aJbK1XePID_9eIdvm4hot8toJxPjTNsckvKo0i86pPSvahb2v5BO42vCqi9SC6MnqccDIsu_biy-LnW1AE3ZrvPMiWKsRoIKrcl5PihL8zZ0jF2Wb8Vy2JVqyhZnO4tri-_HO13TR8BiYn5D_F5yVIWX4HfaAv7AgOOE4', 
    ARRAY[
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAuMYZGll9TAUgo3uh5WTyuuk5iDzX2SpaYr0sLVD4ZQt1LknY_hkZGU7s408zpoO9gtoEotvkK_8-k7ur1E0b_tgQDTkrZY98fWrwiAfpSUr7welCsUCRGMuTL-I4QfXW9JVyfkxH1YWbq3VEZ2_KL2He9lYUmnPo6cofKng5I70ja_kgRvEwAh8cn-sX8Fot1_WH2XNxtr4Z6gKYhcGoKLPBx1DElt889OirE2UUL2KiYlnSAFs7bn_ZWf360CkBbbUWuKpVEPgwB'
    ], 
    '{"mileage": "22.3 kmpl", "engine_capacity": "1197 cc", "max_power": "89 bhp @ 6000 rpm"}'::jsonb
),
(
    'swift-2021', 'Maruti Suzuki', 'Swift', 'ZXi+ AMT', 2021, 22500, 'Petrol', 'Automatic', 
    6.90, 'Jhunsi, Prayagraj', true, false, 'Premium', '1197 cc, K-Series', 
    '88 bhp @ 6000 rpm', '5 Seater', 'First Owner', 'Third Party (Valid Aug 2025)', 
    'Vibrant Maruti Suzuki Swift ZXi+ with advanced automated manual transmission (AMT). Excellent mileage, sporty red exteriors, and a certified history.', 
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAMc7G0-yFUSIy1FCLlzMieF021GjDoSVWSUJMl6MImts91jJSWwXV6ifvoVt_Jgl0tv_YkQmhoV3umZstG4fk-aGA7ronJPr1nKltIccfO_COw5vzusAxs6CCO0ukHRAYhXOTE_fCte62QrjFnq16zXPWilEbBn0ZbMqAHXtsJbAmFZalWDEZuSXO6VjUHTHW3HXwIinW1Dab1ddx7kg277XZSRKUb5WdkZ-ngmptL69Ocsis8fL2PKaNkDuiQrN8nAXH__TLbZn8P', 
    ARRAY[
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDw93X-LkMwsrvg-HAnDfcsAMMmvBMBec8p7UUoKfXWQmuM6tvkuw2VioRxAKJa7P6Jn3s6ktwsM6_EBeePSYacTB7AUb_vW3Hba5KoexLismGLtb0J3AvXQ0-q6GSJqd4dbLfP4eNW8XCyeoh4Twyolf9BATR3Bn8SBQATyfUoVfMZ-UDZAO_Ym0V53RVkyvOZjELsm2ewN7Oi7WVsYBv-mREcNfF6va0XVQY2szmJ_4QaQKmyLK3OfdqS7_IKZz1ZMxku-HuHxEf4'
    ], 
    '{"mileage": "20.8 kmpl", "engine_capacity": "1197 cc", "max_power": "88 bhp @ 6000 rpm"}'::jsonb
),
(
    'ciaz-2019', 'Maruti Suzuki', 'Ciaz', 'Delta Smart Hybrid', 2019, 45000, 'Diesel', 'Manual', 
    9.25, 'Jhunsi, Prayagraj', true, false, 'Premium', '1498 cc, DDiS 225', 
    '94 bhp @ 4000 rpm', '5 Seater', 'First Owner', 'Comprehensive (Valid Dec 2025)', 
    'Classy silver sedan with maximum rear legroom and luxury comfort. Economical diesel engine with Smart Hybrid assistance for great range.', 
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBddA8oPIJszQLm2z0omaYf2DQsOBK23SWk2uR8qF3cMF0vCt_cLjmUADyzm9FB6I1U7mjePsQni80y07WBZ64-YLDgBk0WhdsUj_3l2Py7C7jV1jTsa0h7uNYxqakfc6okTUvbgUfBmEnE6Iu1igi3vk13bKV2gti3pJR_yt1tGJprT7yjVSWAUzC0eahjhV_17-jaMUTyvEO-WuXp76UCWfyWym1uT4WgGdkOGq0AqLnYQkESDqzCp8VRAS_sJh9qsRpNN-fiYxHw', 
    ARRAY[]::text[], 
    '{"mileage": "21.2 kmpl", "engine_capacity": "1498 cc", "max_power": "94 bhp @ 4000 rpm"}'::jsonb
),
(
    'grand-vitara-2023', 'Maruti Suzuki', 'Grand Vitara', 'Intelligent Hybrid', 2023, 5800, 'Petrol', 'Automatic', 
    18.10, 'Jhunsi, Prayagraj', true, true, 'New Arrival', '1490 cc, M15A', 
    '91 bhp @ 5500 rpm', '5 Seater', 'First Owner', 'Comprehensive (Valid Jan 2026)', 
    'Next-generation hybrid SUV with e-CVT and silent electric drive option. Loaded with sunroof, 360-degree camera, and advanced safety features.', 
    'https://lh3.googleusercontent.com/aida-public/AB6AXuB_13V0IHbsVbBh9W9xqdRHVpGYo_hfku6Ysdrq_JHCINzumVzaDty6DvArh9zpvtPbwrZBX6FSJcMpXpUXfKlNI9DCbtHfcBaNx9fe08AqPxg4bfQfWhC5pQvY8Rob87bEoPnzy_CxVfiLl_CRAlHODmOCAgu7vC6nTp057KThcHnbnRnr4PoHW0WUGzoADSUi_Xo9-ysfC-HCD_C6Cbel5v6tEulIU3eBZaaA6lHeuqTWZkfrzj3eJSsxTqFOXSIqvUS24HWdkun6', 
    ARRAY[
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBeztXZYwHSjAYAuwMTG9zj2g7VXgCy6uqV6RzwXuZmEO9SxyxRvKcyEXX8ylESfe8QahLI1dmJrAi2f_upYfWTwsf3fSCQqRj4nFnVvNQen3WnFg7P5j-5MsUlXZwQMP4IgquMialGqv_Q5qksfTRD2mbDJLzToGbDfvFnCQqN0atzyAKhgRpANM_iYfX_XAAHiLq_eNdngufwIidQI3flsc4jvsi6qsaYPDqNwv3BWicfQacKWAXrw1bPhqxGeG4PIpjo6PZGhNXG'
    ], 
    '{"mileage": "27.9 km/l", "engine_capacity": "1490 cc", "max_power": "91 bhp @ 5500 rpm"}'::jsonb
);
